#!/bin/zsh



# weterm path
export PATH="$PATH:/Applications/WezTerm.app/Contents/MacOS"

# cargo for Rust. ( Add path script $HOME/.cargo/bin )
source /Users/koki/.cargo/env

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"


# go 
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# nodenv 
export PATH="$HOME/.nodenv/bin:$PATH"
eval "$(nodenv init -)"